name: PostgreSQL
on: [push]
jobs:
  Test-With-PostgreSQL:
    runs-on: ubuntu-latest
    container: ruby:3.2
    strategy:
      fail-fast: false
    env:
      DATABASE_ADAPTER: postgresql
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Update bundler
        run: gem update bundler # Use the latest bundler
      - name: Bundle dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test
